vkontakte_login:
    pattern: /authorization/check-vkontakte

vkontakte_connect:
    pattern: /connect/check-vkontakte

github_login:
    pattern: /authorization/check-github

github_connect:
    pattern: /connect/check-github

facebook_login:
    pattern: /authorization/check-facebook

facebook_connect:
    pattern: /connect/check-facebook

google_login:
    pattern: /authorization/check-google

google_connect:
    pattern: /connect/check-google

registration_step_2:
    path: /registration-step-2
    defaults: { _controller: NetworkOAuthBundle:Registration:registrationStep2}

show_links:
    path: /link/all
    defaults: { _controller: NetworkOAuthBundle:Links:showLinks}

remove_link:
    path: /link/remove/{service}
    defaults: { _controller: NetworkOAuthBundle:Links:removeLink}
