services:
  network_store.relationship_manager:
      class: Network\StoreBundle\Service\RelationshipManager
      arguments: [ "@doctrine.orm.entity_manager", "@security.context" ]

  network_store.form.type.job:
      class: Network\StoreBundle\Form\Type\JobType
      tags:
          - { name: form.type, alias: job }

  network_store.form.type.job_post:
    class: Network\StoreBundle\Form\Type\JobPostType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
        - { name: form.type, alias: network_storebundle_job_post }

  network.store.form.type.category:
      class: Network\StoreBundle\Form\Type\CategoryType
      tags:
          - { name: form.type, alias: category }
      arguments: ["@sonata.admin.manager.orm"]

  network.store.paginator:
      class: Network\StoreBundle\Service\Paginator
      arguments: ["@doctrine.orm.entity_manager"]

  network.store.category_service:
      class: Network\StoreBundle\Service\CategoryService
      calls:
          - [setPaginator, ["@network.store.paginator"]]
      arguments: ["@doctrine.orm.entity_manager"]

  network.store.im_service:
      class: Network\StoreBundle\Service\ImService
      arguments: ["@doctrine.orm.entity_manager"]
  
  network.store.community_service:
      class: Network\StoreBundle\Service\CommunityService
      arguments: ["@doctrine.orm.entity_manager"]
